name: Build AWX EE image

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - 'master'

jobs:
  build-ee-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/thedatabaseme/awx-ee
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install ansible-builder
        run: pip3 install ansible-builder

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build EE image
        run: |
          ansible-builder build \
          --tag ghcr.io/thedatabaseme/awx-ee:latest \
          --tag ${{ steps.meta.outputs.tags }} \
          --container-runtime docker \
          -f execution-environment.yml

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.1
        with:
          image-ref: 'ghcr.io/thedatabaseme/awx-ee:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push EE image
        if: github.ref_type == 'tag'
        run: |
          docker push ghcr.io/thedatabaseme/awx-ee -a
